---
# Program/Department Title
title: Center on Regional Politics
# Subdirectory (with / at only at beginning)
baseurl: /center-on-regional-politics
# Production domain (without / at the end)
production: https://www.cla.temple.edu
# url spits sitemap
url: https://www.cla.temple.edu/center-on-regional-politics
faculty-page: /staff/

# Development Config
# If you do not have access to 'tutheme', use 'minima' instead.
theme: tutheme
palette: light #future feature

# Program Information
# Short tagline for tweets (<100 characters)
tagline: This is our life's work
# Longer descriptions for link previews (<250 characters)
description: 'The Center on Regional Politics provides neutral ground and intellectual resources to encourage and support interaction among leaders throughout southeastern Pennsylvania, with the goal of developing evidence-based policies that respond to the region’s needs and promote its broad civic and economic interests.'
# List of related keywords for search engines
keywords: highered, college, university, philadelphia, Temple

# Address
address:
  building: Anderson Hall
  room: 832
  street: 1114 West Berks St
  city: Philadelphia, PA 19122
  email: corp@temple.edu
  phone: 215-204-1600

# University & College Information
university:
  name: Temple University
  url: https://temple.edu/
college:
  name: College of Liberal Arts
  url: https://liberalarts.temple.edu/
  
program_news: https://liberalarts.temple.edu/news/center-on-regional-politics
  
# CSV/JSON/YAML data feeds URLs, to be fetched before each build
events-feed: https://liberalarts.temple.edu/events/center-on-regional-politics/csv
news-feed: https://liberalarts.temple.edu/news/center-on-regional-politics/csv
articles-feed: https://liberalarts.temple.edu/articles/center-on-regional-politics/csv
faculty-feed: https://liberalarts.temple.edu/profiles/center-on-regional-politics/csv
media-mentions-feed: https://liberalarts.temple.edu/media-mentions/center-on-regional-politics/csv

# Social Media
# Put in only the username unless otherwise noted
# If social media does not apply to your department, keep it blank or use the default values.
social:
  # Facebook - https://facebook.com/USERNAME
  # if your page does not have a custom URL, create one!
  facebook: TempleLiberalArts
  # Twitter - http://twitter.com/TempleCORP
  twitter: TULiberalArts
  # Instagram - https://www.instagram.com/USERNAME
  instagram: TULiberalArts
  # Snapchat - USERNAME
  snapchat:
  # GitHub - https://github.com/USERNAME or https://github.com/USERNAME/REPO
  github:
  # DeviantArt - http://USERNAME.deviantart.com/
  deviantart:
  # Vimeo - https://vimeo.com/USERNAME
  vimeo:
  # YouTube - Paste the FULL URL below
  youtube:
  # LinkedIn - Paste the FULL URL below
  linkedin:
  # Slack - Paste the FULL URL below
  slack:
  # Google Tag Manager OR Google Analytics
  google_analytics:
  google_tag_manager: GTM-58ZL5B


# Global Site Config
# DO NOT edit below unless if you know what you're doing!
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    layout: page
permalink: /:title

# Prose
prose:
  rooturl: pages
  media: media
  ignore:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - index.html
  - _config.yml
  metadata:
    pages:
      - name: title
        field:
          element: text
          label: Title
      - name: permalink
        field:
          element: text
          label: Permalink
      - name: layout
        field:
          element: select
          label: Page layout
          options:
            - name: page
              value: page
            - name: faculty
              value: faculty
            - name: home
              value: home

# Jekyll Ignore
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - s3_website.yml
  - .sass-cache
  - .travis.yml
  - .ruby-version
  - .gitignore
  - vendor
  - _site
  - node_modules
